import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms and Conditions — FlockPilot",
  description:
    "Terms and Conditions for using FlockPilot, the poultry farm management and ERP platform operated by Enro Agro Limited.",
  alternates: { canonical: "https://flockpilot.com/terms-and-conditions" },
  openGraph: {
    title: "Terms and Conditions — FlockPilot by Enro Agro Limited",
    description:
      "Terms and Conditions governing the use of the FlockPilot platform.",
    url: "https://flockpilot.com/terms-and-conditions",
  },
};

const tocItems = [
  { id: "definitions", label: "Definitions" },
  { id: "eligibility", label: "Eligibility & Account Registration" },
  { id: "subscription", label: "Subscription Plans & Billing" },
  { id: "cancellation", label: "Cancellation, Expiry & Data Lifecycle" },
  { id: "refund", label: "Refund Policy" },
  { id: "admin-responsibilities", label: "Tenant Administrator Responsibilities" },
  { id: "acceptable-use", label: "Acceptable Use & Prohibited Conduct" },
  { id: "intellectual-property", label: "Intellectual Property" },
  { id: "data-ownership", label: "Your Data & Farm Data Ownership" },
  { id: "third-party", label: "Third-Party Services" },
  { id: "availability", label: "Platform Availability & Maintenance" },
  { id: "disclaimers", label: "Disclaimers & Warranties" },
  { id: "liability", label: "Limitation of Liability" },
  { id: "indemnification", label: "Indemnification" },
  { id: "termination", label: "Termination" },
  { id: "governing-law", label: "Governing Law & Dispute Resolution" },
  { id: "changes", label: "Changes to These Terms" },
  { id: "contact", label: "Contact Us" },
];

const definitions = [
  {
    term: "\u201cPlatform\u201d / \u201cService\u201d",
    desc: "The FlockPilot farm management and ERP SaaS application, including the web interface, mobile application (Android and iOS), API, and all associated features and functionality.",
  },
  {
    term: "\u201cTenant\u201d",
    desc: "An organization (farm business, agribusiness company, or individual operator) that has registered a FlockPilot account and subscribes to the Service.",
  },
  {
    term: "\u201cTenant Administrator\u201d / \u201cAdmin\u201d",
    desc: "The individual who registers the Tenant account and holds the highest level of administrative access within that Tenant\u2019s workspace.",
  },
  {
    term: "\u201cUser\u201d",
    desc: "Any individual authorized by a Tenant Administrator to access and use FlockPilot, including farm managers, supervisors, operators, HR personnel, and finance staff.",
  },
  {
    term: "\u201cTenant Data\u201d / \u201cFarm Data\u201d",
    desc: "All data submitted, uploaded, entered, or generated by a Tenant or its Users within the Platform, including flock records, financial entries, HR records, and operational logs.",
  },
  {
    term: "\u201cSubscription\u201d",
    desc: "A recurring paid plan granting a Tenant access to the Platform for a defined billing period.",
  },
  {
    term: "\u201cBilling Cycle\u201d",
    desc: "The period for which a Subscription fee is charged \u2014 monthly or annually, as selected at signup.",
  },
  {
    term: "\u201cJournal Entry\u201d",
    desc: "A double-entry accounting record automatically or manually generated within the Platform\u2019s Finance module.",
  },
];

function SectionNumber({ n }: { n: number }) {
  return (
    <span className="mb-2 block text-xs font-bold uppercase tracking-[0.15em] text-brand-light">
      {String(n).padStart(2, "0")}
    </span>
  );
}

function Arrow() {
  return <span className="text-brand-light">&rarr;</span>;
}

function ListItem({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex gap-2">
      <Arrow />
      <span>{children}</span>
    </li>
  );
}

export default function TermsAndConditionsPage() {
  return (
    <main className="min-h-screen bg-brand-deep text-white">
      {/* Nav */}
      <nav className="border-b border-white/10 px-6 py-4">
        <div className="mx-auto flex max-w-6xl items-center justify-between">
          <Link href="/" className="text-xl font-bold text-brand-light">
            FlockPilot
          </Link>
          <div className="flex gap-6 text-sm text-white/70">
            <Link href="/features" className="hover:text-white">Features</Link>
            <Link href="/pricing" className="hover:text-white">Pricing</Link>
            <Link href="/ai-assistant" className="hover:text-white">AI Assistant</Link>
            <Link href="/about" className="hover:text-white">About</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="border-b border-white/10 px-6 py-20">
        <div className="mx-auto max-w-3xl">
          <span className="mb-4 inline-block rounded-full bg-brand-light/10 px-4 py-1 text-xs font-semibold uppercase tracking-widest text-brand-light">
            Legal Document
          </span>
          <h1 className="mb-4 text-4xl font-extrabold leading-tight tracking-tight md:text-5xl">
            Terms and <span className="text-brand-light">Conditions</span>
          </h1>
          <p className="max-w-xl text-base leading-relaxed text-white/60">
            These Terms and Conditions constitute a legally binding agreement between you and{" "}
            <strong className="text-white">Enro Agro Limited</strong>, the operator of the FlockPilot farm management
            and ERP platform.
          </p>
          <div className="mt-8 flex flex-wrap gap-8 text-sm">
            <div>
              <span className="block text-[11px] font-semibold uppercase tracking-wider text-white/40">Effective Date</span>
              <span className="text-white/70">1 April 2025</span>
            </div>
            <div>
              <span className="block text-[11px] font-semibold uppercase tracking-wider text-white/40">Last Updated</span>
              <span className="text-white/70">1 April 2025</span>
            </div>
            <div>
              <span className="block text-[11px] font-semibold uppercase tracking-wider text-white/40">Version</span>
              <span className="text-white/70">1.0</span>
            </div>
          </div>
        </div>
      </section>

      {/* Content */}
      <div className="mx-auto max-w-3xl px-6 py-16">
        {/* Intro notice */}
        <div className="mb-10 rounded-lg border-l-2 border-brand-light bg-brand-light/5 px-5 py-4 text-sm text-white/70">
          By registering for, accessing, or using FlockPilot &mdash; whether through our web application, mobile
          application, or API &mdash; you confirm that you have read, understood, and agree to be bound by these Terms
          and our <Link href="/privacy-policy" className="text-brand-light hover:underline">Privacy Policy</Link>, which
          is incorporated herein by reference. If you are accepting these Terms on behalf of an organization, you
          represent that you have the authority to bind that organization.{" "}
          <strong className="text-white">If you do not agree to these Terms, do not use FlockPilot.</strong>
        </div>

        {/* Table of Contents */}
        <div className="mb-14 rounded-2xl border border-white/10 bg-white/[0.03] p-6 md:p-8">
          <h3 className="mb-4 text-sm font-bold uppercase tracking-wider text-brand-light">Table of Contents</h3>
          <ol className="grid gap-2 md:grid-cols-2">
            {tocItems.map((item, i) => (
              <li key={item.id} className="text-sm">
                <a href={`#${item.id}`} className="text-white/60 transition hover:text-brand-light">
                  <span className="mr-1.5 font-semibold text-brand-light/60">{String(i + 1).padStart(2, "0")}.</span>
                  {item.label}
                </a>
              </li>
            ))}
          </ol>
        </div>

        {/* S1 — Definitions */}
        <section id="definitions" className="mb-14 scroll-mt-24">
          <SectionNumber n={1} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Definitions</h2>
          <p className="mb-4 text-white/70">The following definitions apply throughout these Terms:</p>
          <div className="space-y-4">
            {definitions.map((d) => (
              <div key={d.term} className="rounded-xl border border-white/5 bg-white/[0.02] px-5 py-3">
                <dt className="mb-1 text-sm font-semibold text-white">{d.term}</dt>
                <dd className="text-sm text-white/60">{d.desc}</dd>
              </div>
            ))}
          </div>
        </section>

        {/* S2 — Eligibility & Account Registration */}
        <section id="eligibility" className="mb-14 scroll-mt-24">
          <SectionNumber n={2} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Eligibility &amp; Account Registration</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">2.1 Eligibility</h3>
          <p className="mb-4 text-white/70">
            To use FlockPilot, you must be at least 18 years of age and capable of entering into a legally binding
            contract under the laws of the Federal Republic of Nigeria. FlockPilot is a professional business tool
            intended for commercial and agricultural business use only. It is not designed for or directed at children.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">2.2 Account Registration</h3>
          <p className="mb-4 text-white/70">
            To access the Platform, you must register a Tenant account by providing accurate, current, and complete
            information. You agree to keep this information up to date at all times. Each Tenant organization should
            maintain a single account; creating multiple accounts to circumvent platform limits or pricing is prohibited.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">2.3 Account Security</h3>
          <p className="mb-4 text-white/70">
            You are responsible for maintaining the confidentiality of your login credentials and for all activities
            that occur under your account. You must notify us immediately at{" "}
            <strong className="text-white">hello@flockpilot.com</strong> if you suspect any unauthorized access to your
            account. We are not liable for any loss or damage arising from your failure to protect your credentials.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">2.4 Tenant Administrator Responsibility</h3>
          <p className="text-white/70">
            The Tenant Administrator is responsible for managing Users within their workspace, including inviting,
            assigning roles to, and removing Users. The Tenant Administrator accepts these Terms on behalf of all Users
            within their organization. It is the Tenant Administrator&apos;s responsibility to ensure all Users comply
            with these Terms.
          </p>
        </section>

        {/* S3 — Subscription Plans & Billing */}
        <section id="subscription" className="mb-14 scroll-mt-24">
          <SectionNumber n={3} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Subscription Plans &amp; Billing</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">3.1 Subscription Plans</h3>
          <p className="mb-4 text-white/70">
            FlockPilot is offered on a subscription basis. Available plans, pricing, and included features are described
            on our <Link href="/pricing" className="text-brand-light hover:underline">pricing page</Link>. We reserve
            the right to modify, add, or remove plans at any time, with reasonable notice to existing subscribers.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">3.2 Payment</h3>
          <p className="mb-4 text-white/70">
            All subscription fees are billed in advance for each Billing Cycle and are processed through{" "}
            <strong className="text-white">Paystack</strong>, our authorized payment gateway. By subscribing, you
            authorize us (via Paystack) to charge your designated payment method on a recurring basis at the start of
            each Billing Cycle.
          </p>
          <p className="mb-4 text-white/70">
            All fees are quoted and charged in <strong className="text-white">Nigerian Naira (NGN)</strong> unless
            otherwise stated. Applicable taxes (including VAT where required by Nigerian law) will be added to the
            subscription fee.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">3.3 Failed Payments</h3>
          <p className="mb-4 text-white/70">
            If a payment fails, we will attempt to retry the charge. If payment cannot be collected after reasonable
            retry attempts, your subscription may be suspended or downgraded. We will notify you via email and/or in-app
            notification before any suspension takes effect.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">3.4 Price Changes</h3>
          <p className="mb-4 text-white/70">
            We may change subscription pricing at any time. For existing subscribers, price changes will take effect at
            the start of the next Billing Cycle following at least 30 days&apos; written notice via email to the Tenant
            Administrator.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">3.5 Free Trials</h3>
          <p className="text-white/70">
            Where a free trial is offered, access to the Platform during the trial period is subject to these Terms. At
            the end of the trial period, your subscription will automatically convert to a paid plan unless you cancel
            before the trial expires.
          </p>
        </section>

        {/* S4 — Cancellation, Expiry & Data Lifecycle */}
        <section id="cancellation" className="mb-14 scroll-mt-24">
          <SectionNumber n={4} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Cancellation, Expiry &amp; Data Lifecycle</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">4.1 Cancellation by You</h3>
          <p className="mb-4 text-white/70">
            You may cancel your subscription at any time through your account settings or by contacting{" "}
            <strong className="text-white">hello@flockpilot.com</strong>. Cancellation takes effect at the end of the
            current Billing Cycle. You will retain access to the Platform until the end of the paid period.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">4.2 Subscription Lifecycle States</h3>
          <p className="mb-4 text-white/70">Your subscription progresses through the following states:</p>
          <ul className="mb-4 space-y-2 text-white/70">
            <ListItem><strong className="text-white">ACTIVE:</strong> Your subscription is current and all Platform features are fully accessible.</ListItem>
            <ListItem><strong className="text-white">CANCELLED:</strong> You have cancelled but the paid period has not yet ended. Full access continues until the period expires. No further charges are made.</ListItem>
            <ListItem><strong className="text-white">EXPIRED:</strong> The paid period has ended. Your account enters a read-only grace period. You may view but not add or edit data. You may reactivate your subscription during this period to restore full access.</ListItem>
            <ListItem><strong className="text-white">PURGED:</strong> After the grace period expires without reactivation, your Tenant Data is scheduled for permanent deletion. This action is irreversible.</ListItem>
          </ul>

          <h3 className="mb-2 mt-6 text-lg font-semibold">4.3 Data Export Before Cancellation</h3>
          <p className="mb-4 text-white/70">
            We strongly recommend that you export all Tenant Data before your subscription enters the EXPIRED state.
            FlockPilot provides data export functionality within the Platform. We are not liable for any data loss
            resulting from failure to export data before the PURGED state is reached.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">4.4 Retention of Financial Records</h3>
          <p className="text-white/70">
            Notwithstanding the above, certain financial records (journal entries, payroll records, invoices) may be
            retained for up to <strong className="text-white">7 years</strong> following account closure in accordance
            with Nigerian tax and accounting regulations. Such records are retained in anonymized or archived form and
            are not accessible to you after account deletion, but may be produced in response to a lawful regulatory
            request.
          </p>
        </section>

        {/* S5 — Refund Policy */}
        <section id="refund" className="mb-14 scroll-mt-24">
          <SectionNumber n={5} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Refund Policy</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">5.1 General Policy</h3>
          <p className="mb-4 text-white/70">
            All subscription fees are non-refundable except as expressly stated in these Terms or as required by
            applicable Nigerian consumer protection law. We do not provide prorated refunds for partial Billing Cycles
            upon cancellation.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">5.2 Exceptions</h3>
          <p className="mb-4 text-white/70">We will consider refund requests in the following circumstances:</p>
          <ul className="mb-4 space-y-2 text-white/70">
            <ListItem>A verifiable technical error on our part caused the Platform to be inaccessible for a significant portion of the Billing Cycle (generally more than 72 consecutive hours)</ListItem>
            <ListItem>A duplicate charge was made to your account due to a billing system error</ListItem>
            <ListItem>A charge was made after a confirmed cancellation was processed</ListItem>
          </ul>
          <p className="mb-4 text-white/70">
            To request a refund, contact <strong className="text-white">hello@flockpilot.com</strong> within 14 days of
            the charge in question. We will review and respond within 10 business days.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">5.3 Free Trial Charges</h3>
          <p className="text-white/70">
            If you are charged after a free trial and did not intend to continue, contact us within 7 days of the charge
            and we will consider a full refund at our discretion.
          </p>
        </section>

        {/* S6 — Tenant Administrator Responsibilities */}
        <section id="admin-responsibilities" className="mb-14 scroll-mt-24">
          <SectionNumber n={6} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Tenant Administrator Responsibilities</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">6.1 User Management</h3>
          <p className="mb-4 text-white/70">
            Tenant Administrators are responsible for all Users added to their workspace. This includes ensuring that
            all Users are legitimate employees or authorized agents of the Tenant organization, assigning appropriate
            roles and permissions, and promptly removing access for Users who leave the organization or should no longer
            have access.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">6.2 Data Accuracy</h3>
          <p className="mb-4 text-white/70">
            FlockPilot&apos;s Finance module auto-generates accounting journal entries from farm operational events (feed
            consumption, mortality, sales, etc.). Tenant Administrators and authorized finance users are responsible for
            reviewing, verifying, and approving these entries. We are not liable for financial reporting errors arising
            from inaccurate data entered by Users.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">6.3 Compliance</h3>
          <p className="mb-4 text-white/70">
            Tenant Administrators are responsible for ensuring that their use of FlockPilot &mdash; and the data entered
            into the Platform &mdash; complies with all applicable laws and regulations, including Nigerian tax law
            (PAYE, VAT, WHT), labour law, and data protection law. FlockPilot provides tools to assist with compliance
            but does not constitute legal, tax, or accounting advice.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">6.4 Separation of Duties</h3>
          <p className="text-white/70">
            Tenant Administrators are responsible for configuring appropriate role-based access controls within their
            workspace to maintain separation of duties, particularly between operational roles (farm managers,
            supervisors, operators) and financial roles (accountants, finance managers). We strongly recommend that
            operational submissions and financial approvals be performed by distinct roles within your organization.
          </p>
        </section>

        {/* S7 — Acceptable Use & Prohibited Conduct */}
        <section id="acceptable-use" className="mb-14 scroll-mt-24">
          <SectionNumber n={7} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Acceptable Use &amp; Prohibited Conduct</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">7.1 Permitted Use</h3>
          <p className="mb-4 text-white/70">
            FlockPilot is licensed to you for your legitimate internal business use in managing your farm or agribusiness
            operations. You may not resell, sublicense, or white-label the Platform without our express written consent.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">7.2 Prohibited Conduct</h3>
          <p className="mb-4 text-white/70">You agree not to:</p>
          <ul className="mb-4 space-y-2 text-white/70">
            <ListItem>Use the Platform for any unlawful purpose or in violation of any applicable law or regulation</ListItem>
            <ListItem>Enter false, fraudulent, or misleading data into the Platform</ListItem>
            <ListItem>Attempt to gain unauthorized access to any part of the Platform, other Tenant workspaces, or our infrastructure</ListItem>
            <ListItem>Reverse engineer, decompile, disassemble, or attempt to derive the source code of the Platform</ListItem>
            <ListItem>Scrape, crawl, or use automated means to extract data from the Platform without our written consent</ListItem>
            <ListItem>Introduce malware, viruses, or any other harmful code into the Platform</ListItem>
            <ListItem>Circumvent, disable, or interfere with any security features of the Platform</ListItem>
            <ListItem>Use the Platform in a way that disrupts, degrades, or impairs access for other users</ListItem>
            <ListItem>Create multiple Tenant accounts to circumvent pricing, limits, or any suspension or termination</ListItem>
            <ListItem>Use the Platform to store or transmit content that is illegal, defamatory, or infringes the intellectual property rights of any third party</ListItem>
          </ul>
          <p className="text-white/70">
            Violation of this section may result in immediate suspension or termination of your account without notice
            and without refund.
          </p>
        </section>

        {/* S8 — Intellectual Property */}
        <section id="intellectual-property" className="mb-14 scroll-mt-24">
          <SectionNumber n={8} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Intellectual Property</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">8.1 Our Intellectual Property</h3>
          <p className="mb-4 text-white/70">
            FlockPilot, including its software, design, architecture, features, documentation, trademarks, and all
            content we create, is the exclusive intellectual property of Enro Agro Limited. These Terms do not transfer
            any ownership rights to you. You are granted a limited, non-exclusive, non-transferable, revocable licence
            to access and use the Platform solely in accordance with these Terms.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">8.2 Your Intellectual Property</h3>
          <p className="mb-4 text-white/70">
            You retain full ownership of all Tenant Data you enter into the Platform. You grant us a limited,
            non-exclusive licence to store, process, and use your Tenant Data solely for the purpose of providing and
            improving the Service as described in our{" "}
            <Link href="/privacy-policy" className="text-brand-light hover:underline">Privacy Policy</Link>. We do not
            claim any ownership over your farm data, financial records, or any other content you create.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">8.3 Feedback</h3>
          <p className="text-white/70">
            If you provide us with suggestions, ideas, or feedback about the Platform (&quot;Feedback&quot;), you grant
            us an unrestricted, perpetual, royalty-free licence to use that Feedback in any way, including incorporating
            it into the Platform, without any obligation to compensate you.
          </p>
        </section>

        {/* S9 — Your Data & Farm Data Ownership */}
        <section id="data-ownership" className="mb-14 scroll-mt-24">
          <SectionNumber n={9} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Your Data &amp; Farm Data Ownership</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">9.1 Data Ownership</h3>
          <p className="mb-4 text-white/70">
            As stated in Section 8.2, you own your Tenant Data. FlockPilot acts as a data processor on your behalf. We
            do not sell, share, or use your farm operational or financial data for any purpose other than delivering the
            Service.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">9.2 Data Export</h3>
          <p className="mb-4 text-white/70">
            You may export your Tenant Data at any time using the Platform&apos;s built-in export functionality. It is
            your responsibility to maintain backup copies of your data.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">9.3 Aggregated &amp; Anonymized Data</h3>
          <p className="mb-4 text-white/70">
            We may use aggregated and fully anonymized data derived from Platform usage &mdash; in a form that cannot
            identify you or your organization &mdash; for platform improvement, benchmarking, and research purposes.
            This does not include any personally identifiable or competitively sensitive data.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">9.4 Data Processing</h3>
          <p className="text-white/70">
            Our collection and use of personal data is governed by our{" "}
            <Link href="/privacy-policy" className="text-brand-light hover:underline">Privacy Policy</Link>, which forms
            part of these Terms. By using FlockPilot, you agree to the data practices described therein.
          </p>
        </section>

        {/* S10 — Third-Party Services */}
        <section id="third-party" className="mb-14 scroll-mt-24">
          <SectionNumber n={10} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Third-Party Services</h2>
          <p className="mb-4 text-white/70">
            FlockPilot integrates with third-party services to deliver its functionality, including:
          </p>
          <ul className="mb-4 space-y-2 text-white/70">
            <ListItem><strong className="text-white">Paystack</strong> &mdash; payment processing</ListItem>
            <ListItem><strong className="text-white">Termii</strong> &mdash; SMS and WhatsApp notifications</ListItem>
            <ListItem><strong className="text-white">Sentry</strong> &mdash; error monitoring and platform reliability</ListItem>
          </ul>
          <p className="mb-4 text-white/70">
            Your use of these third-party services through FlockPilot is subject to their respective terms of service
            and privacy policies. We are not responsible for the acts or omissions of any third-party service provider.
            Any disputes regarding payment processing should be directed to Paystack in the first instance.
          </p>
          <p className="text-white/70">
            FlockPilot may also contain links to third-party websites or resources. We do not endorse and are not
            responsible for any third-party content, products, or services accessible through such links.
          </p>
        </section>

        {/* S11 — Platform Availability & Maintenance */}
        <section id="availability" className="mb-14 scroll-mt-24">
          <SectionNumber n={11} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Platform Availability &amp; Maintenance</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">11.1 Uptime</h3>
          <p className="mb-4 text-white/70">
            We strive to provide a reliable, high-availability platform. However, we do not guarantee uninterrupted or
            error-free access to FlockPilot. The Platform is provided on an &quot;as available&quot; basis.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">11.2 Scheduled Maintenance</h3>
          <p className="mb-4 text-white/70">
            We may take the Platform offline for scheduled maintenance. Where possible, we will provide advance notice
            of planned downtime via in-app notification and/or email. We will endeavor to perform maintenance during
            off-peak hours.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">11.3 Unplanned Outages</h3>
          <p className="text-white/70">
            In the event of an unplanned outage, we will work to restore the Service as quickly as reasonably possible.
            We are not liable for any losses or damages arising from Platform downtime, whether scheduled or unplanned,
            beyond what is expressly provided in our refund policy in Section 5.
          </p>
        </section>

        {/* S12 — Disclaimers & Warranties */}
        <section id="disclaimers" className="mb-14 scroll-mt-24">
          <SectionNumber n={12} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Disclaimers &amp; Warranties</h2>
          <p className="mb-4 text-white/70">
            To the maximum extent permitted by applicable law, FlockPilot is provided{" "}
            <strong className="text-white">&quot;as is&quot; and &quot;as available&quot;</strong> without warranties of
            any kind, whether express, implied, or statutory.
          </p>
          <p className="mb-4 text-white/70">We specifically disclaim all implied warranties of:</p>
          <ul className="mb-4 space-y-2 text-white/70">
            <ListItem>Merchantability or fitness for a particular purpose</ListItem>
            <ListItem>Uninterrupted, timely, secure, or error-free operation</ListItem>
            <ListItem>Accuracy or completeness of any financial calculations, reports, or journal entries generated by the Platform</ListItem>
          </ul>
          <div className="rounded-lg border-l-2 border-brand-light bg-brand-light/5 px-5 py-4 text-sm text-white/70">
            <strong className="text-white">FlockPilot is not a substitute for professional accounting, legal, tax, or
            veterinary advice.</strong> The Finance and HR modules are tools to assist your operations &mdash; you remain
            responsible for the accuracy of your financial records and compliance with applicable law. We strongly
            recommend engaging qualified professional advisors for your accounting and legal needs.
          </div>
        </section>

        {/* S13 — Limitation of Liability */}
        <section id="liability" className="mb-14 scroll-mt-24">
          <SectionNumber n={13} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Limitation of Liability</h2>
          <p className="mb-4 text-white/70">
            To the maximum extent permitted by Nigerian law, Enro Agro Limited and its officers, directors, employees,
            and agents shall not be liable for any:
          </p>
          <ul className="mb-4 space-y-2 text-white/70">
            <ListItem>Indirect, incidental, special, consequential, or punitive damages</ListItem>
            <ListItem>Loss of profits, revenue, data, goodwill, or business opportunities</ListItem>
            <ListItem>Damages arising from unauthorized access to or alteration of your Tenant Data</ListItem>
            <ListItem>Damages arising from reliance on financial reports, journal entries, or payroll calculations generated by the Platform</ListItem>
            <ListItem>Damages arising from any third-party service failure (including Paystack or Termii)</ListItem>
          </ul>
          <p className="mb-4 text-white/70">
            In any event, our total aggregate liability to you for all claims arising under or related to these Terms
            shall not exceed the total subscription fees paid by you to FlockPilot in the{" "}
            <strong className="text-white">three (3) months</strong> immediately preceding the event giving rise to
            the claim.
          </p>
          <p className="text-white/70">
            Nothing in these Terms shall limit our liability for death or personal injury caused by our negligence,
            fraud, or any other liability that cannot be excluded by law.
          </p>
        </section>

        {/* S14 — Indemnification */}
        <section id="indemnification" className="mb-14 scroll-mt-24">
          <SectionNumber n={14} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Indemnification</h2>
          <p className="mb-4 text-white/70">
            You agree to indemnify, defend, and hold harmless Enro Agro Limited and its officers, directors, employees,
            and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable
            legal fees) arising out of or related to:
          </p>
          <ul className="space-y-2 text-white/70">
            <ListItem>Your use of FlockPilot in violation of these Terms</ListItem>
            <ListItem>Your Tenant Data, including any claim that it infringes the rights of a third party</ListItem>
            <ListItem>Any actions taken by your Users within your Tenant workspace</ListItem>
            <ListItem>Your violation of any applicable law or regulation</ListItem>
          </ul>
        </section>

        {/* S15 — Termination */}
        <section id="termination" className="mb-14 scroll-mt-24">
          <SectionNumber n={15} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Termination</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">15.1 Termination by You</h3>
          <p className="mb-4 text-white/70">
            You may terminate your FlockPilot account at any time by cancelling your subscription through account
            settings or by contacting <strong className="text-white">hello@flockpilot.com</strong>. Termination takes
            effect as described in Section 4.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">15.2 Termination by Us</h3>
          <p className="mb-4 text-white/70">
            We reserve the right to suspend or terminate your account and access to the Platform, with or without
            notice, if:
          </p>
          <ul className="mb-4 space-y-2 text-white/70">
            <ListItem>You breach any provision of these Terms</ListItem>
            <ListItem>You fail to pay subscription fees after reasonable notice</ListItem>
            <ListItem>We believe your use of the Platform poses a security risk, legal risk, or harm to other users</ListItem>
            <ListItem>We are required to do so by law or a competent regulatory authority</ListItem>
            <ListItem>We discontinue the Platform (with at least 60 days&apos; notice where possible)</ListItem>
          </ul>

          <h3 className="mb-2 mt-6 text-lg font-semibold">15.3 Effect of Termination</h3>
          <p className="text-white/70">
            Upon termination for any reason, your right to access the Platform immediately ceases. Provisions of these
            Terms that by their nature should survive termination &mdash; including Sections 8 (Intellectual Property),
            9 (Data Ownership), 12 (Disclaimers), 13 (Limitation of Liability), 14 (Indemnification), and 16 (Governing
            Law) &mdash; shall continue to apply.
          </p>
        </section>

        {/* S16 — Governing Law & Dispute Resolution */}
        <section id="governing-law" className="mb-14 scroll-mt-24">
          <SectionNumber n={16} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Governing Law &amp; Dispute Resolution</h2>

          <h3 className="mb-2 mt-6 text-lg font-semibold">16.1 Governing Law</h3>
          <p className="mb-4 text-white/70">
            These Terms and any dispute arising out of or in connection with them shall be governed by and construed in
            accordance with the laws of the <strong className="text-white">Federal Republic of Nigeria</strong>, without
            regard to its conflict of law principles.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">16.2 Informal Resolution</h3>
          <p className="mb-4 text-white/70">
            Before initiating any formal dispute process, you agree to contact us at{" "}
            <strong className="text-white">hello@flockpilot.com</strong> and give us 30 days to attempt to resolve the
            dispute informally. Most disputes can be resolved quickly this way.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">16.3 Formal Dispute Resolution</h3>
          <p className="mb-4 text-white/70">
            If informal resolution fails, any dispute, controversy, or claim arising out of or relating to these Terms,
            or the breach, termination, or invalidity thereof, shall be submitted to the exclusive jurisdiction of the
            courts of <strong className="text-white">Lagos State, Nigeria</strong>. Both parties submit to the personal
            jurisdiction of those courts.
          </p>

          <h3 className="mb-2 mt-6 text-lg font-semibold">16.4 Waiver of Class Actions</h3>
          <p className="text-white/70">
            You agree that any dispute resolution proceedings will be conducted on an individual basis only, and not as a
            class or representative action.
          </p>
        </section>

        {/* S17 — Changes to These Terms */}
        <section id="changes" className="mb-14 scroll-mt-24">
          <SectionNumber n={17} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Changes to These Terms</h2>
          <p className="mb-4 text-white/70">
            We may update these Terms from time to time. When we make material changes, we will:
          </p>
          <ul className="mb-4 space-y-2 text-white/70">
            <ListItem>Update the &quot;Last Updated&quot; date at the top of this page</ListItem>
            <ListItem>Notify Tenant Administrators via email and/or in-app notification at least <strong className="text-white">14 days</strong> before the changes take effect</ListItem>
            <ListItem>Where required by law, seek your renewed consent</ListItem>
          </ul>
          <p className="text-white/70">
            Your continued use of FlockPilot after the effective date of any updated Terms constitutes your acceptance of
            those changes. If you do not agree to the updated Terms, you must stop using the Platform and cancel your
            subscription before the changes take effect.
          </p>
        </section>

        {/* S18 — Contact Us */}
        <section id="contact" className="mb-14 scroll-mt-24">
          <SectionNumber n={18} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Contact Us</h2>
          <p className="mb-4 text-white/70">
            For any questions, concerns, or notices regarding these Terms, please contact us:
          </p>
          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
            <h4 className="mb-4 text-lg font-bold">Enro Agro Limited (FlockPilot)</h4>
            <div className="divide-y divide-white/5 text-sm">
              <div className="flex gap-4 py-3">
                <span className="w-24 shrink-0 text-xs font-semibold uppercase tracking-wider text-white/40">Email</span>
                <a href="mailto:hello@flockpilot.com" className="text-brand-light hover:underline">hello@flockpilot.com</a>
              </div>
              <div className="flex gap-4 py-3">
                <span className="w-24 shrink-0 text-xs font-semibold uppercase tracking-wider text-white/40">Address</span>
                <span className="text-white/70">2, Creek Road, Apapa, Lagos, Nigeria</span>
              </div>
              <div className="flex gap-4 py-3">
                <span className="w-24 shrink-0 text-xs font-semibold uppercase tracking-wider text-white/40">Website</span>
                <a href="https://flockpilot.com" className="text-brand-light hover:underline">flockpilot.com</a>
              </div>
            </div>
          </div>
          <p className="mt-4 text-sm text-white/50">
            For data protection enquiries specifically, please refer to our{" "}
            <Link href="/privacy-policy" className="text-brand-light hover:underline">Privacy Policy</Link> or contact
            us at the email above marked &quot;Data Privacy.&quot;
          </p>
        </section>
      </div>

      {/* Footer */}
      <footer className="border-t border-white/10 px-6 py-8 text-center text-sm text-white/30">
        &copy; 2025 Enro Agro Limited. All rights reserved. &middot; FlockPilot is a product of Enro Agro Limited,
        registered in Nigeria under the Corporate Affairs Commission (CAC). These Terms were last updated on 1 April 2025.
      </footer>
    </main>
  );
}
