import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — FlockPilot",
  description:
    "How FlockPilot collects, uses, stores, and protects your personal data when you use our farm management platform and mobile application.",
  alternates: { canonical: "https://flockpilot.com/privacy-policy" },
  openGraph: {
    title: "Privacy Policy — FlockPilot by Enro Agro Limited",
    description:
      "How FlockPilot collects, uses, stores, and protects your personal data.",
    url: "https://flockpilot.com/privacy-policy",
  },
};

const tocItems = [
  { id: "who-we-are", label: "Who We Are" },
  { id: "information-we-collect", label: "Information We Collect" },
  { id: "how-we-use-your-information", label: "How We Use Your Information" },
  { id: "legal-basis", label: "Legal Basis for Processing" },
  { id: "data-sharing", label: "Data Sharing & Third Parties" },
  { id: "data-retention", label: "Data Retention" },
  { id: "data-security", label: "Data Security" },
  { id: "your-rights", label: "Your Rights" },
  { id: "childrens-privacy", label: "Children\u2019s Privacy" },
  { id: "cookies", label: "Cookies & Tracking" },
  { id: "international-transfers", label: "International Transfers" },
  { id: "changes", label: "Changes to This Policy" },
  { id: "contact", label: "Contact Us" },
];

const dataCategories = [
  {
    category: "Account & Identity",
    examples: "Full name, email address, phone number, role/job title, profile photo",
    source: "Provided by you or your organization administrator",
  },
  {
    category: "Farm Operational Data",
    examples: "Flock records, feed consumption, mortality logs, production reports, sales records, batch data",
    source: "Entered by users within the platform",
  },
  {
    category: "Financial Data",
    examples: "Journal entries, income/expense records, payroll data, invoice records",
    source: "Entered by users; auto-generated by platform events",
  },
  {
    category: "HR & Payroll Data",
    examples: "Employee names, pay grades, bank details, PAYE/pension records, attendance",
    source: "Entered by HR/admin users",
  },
  {
    category: "Device & Usage Data",
    examples: "IP address, device type, OS version, app version, session duration, feature usage",
    source: "Automatically collected",
  },
  {
    category: "Communication Data",
    examples: "In-app chat messages, notifications, support requests",
    source: "Generated through platform use",
  },
  {
    category: "Payment Data",
    examples: "Subscription plan, billing status, transaction reference (via Paystack)",
    source: "Collected via Paystack payment gateway",
  },
];

const thirdParties = [
  {
    provider: "Paystack",
    purpose: "Subscription billing & payment processing",
    data: "Email, billing info, transaction data",
  },
  {
    provider: "Termii",
    purpose: "SMS & WhatsApp notifications",
    data: "Phone number, message content",
  },
  {
    provider: "Sentry",
    purpose: "Error tracking & platform reliability",
    data: "Anonymized error logs, device/OS info",
  },
  {
    provider: "Cloud Infrastructure",
    purpose: "Hosting, database, and storage",
    data: "All platform data (encrypted at rest)",
  },
];

function SectionNumber({ n }: { n: number }) {
  return (
    <span className="mb-2 block text-xs font-bold uppercase tracking-[0.15em] text-brand-light">
      {String(n).padStart(2, "0")}
    </span>
  );
}

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-brand-deep text-white">
      {/* Nav */}
      <nav className="border-b border-white/10 px-6 py-4">
        <div className="mx-auto flex max-w-6xl items-center justify-between">
          <Link href="/" className="text-xl font-bold text-brand-light">
            FlockPilot
          </Link>
          <div className="flex gap-6 text-sm text-white/70">
            <Link href="/features" className="hover:text-white">Features</Link>
            <Link href="/pricing" className="hover:text-white">Pricing</Link>
            <Link href="/ai-assistant" className="hover:text-white">AI Assistant</Link>
            <Link href="/about" className="hover:text-white">About</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="border-b border-white/10 px-6 py-20">
        <div className="mx-auto max-w-3xl">
          <span className="mb-4 inline-block rounded-full bg-brand-light/10 px-4 py-1 text-xs font-semibold uppercase tracking-widest text-brand-light">
            Legal Document
          </span>
          <h1 className="mb-4 text-4xl font-extrabold leading-tight tracking-tight md:text-5xl">
            Privacy <span className="text-brand-light">Policy</span>
          </h1>
          <p className="max-w-xl text-base leading-relaxed text-white/60">
            This policy explains how FlockPilot collects, uses, stores, and protects your personal
            data when you use our farm management platform and mobile application.
          </p>
          <div className="mt-8 flex flex-wrap gap-8 text-sm">
            <div>
              <span className="block text-[11px] font-semibold uppercase tracking-wider text-white/40">Effective Date</span>
              <span className="text-white/70">1 April 2025</span>
            </div>
            <div>
              <span className="block text-[11px] font-semibold uppercase tracking-wider text-white/40">Last Updated</span>
              <span className="text-white/70">1 April 2025</span>
            </div>
            <div>
              <span className="block text-[11px] font-semibold uppercase tracking-wider text-white/40">Jurisdiction</span>
              <span className="text-white/70">Federal Republic of Nigeria</span>
            </div>
            <div>
              <span className="block text-[11px] font-semibold uppercase tracking-wider text-white/40">Version</span>
              <span className="text-white/70">1.0</span>
            </div>
          </div>
        </div>
      </section>

      {/* Content */}
      <div className="mx-auto max-w-3xl px-6 py-16">
        {/* Table of Contents */}
        <div className="mb-14 rounded-2xl border border-white/10 bg-white/[0.03] p-6 md:p-8">
          <h3 className="mb-4 text-sm font-bold uppercase tracking-wider text-brand-light">Table of Contents</h3>
          <ol className="grid gap-2 md:grid-cols-2">
            {tocItems.map((item, i) => (
              <li key={item.id} className="text-sm">
                <a href={`#${item.id}`} className="text-white/60 transition hover:text-brand-light">
                  <span className="mr-1.5 font-semibold text-brand-light/60">{String(i + 1).padStart(2, "0")}.</span>
                  {item.label}
                </a>
              </li>
            ))}
          </ol>
        </div>

        {/* S1 — Who We Are */}
        <section id="who-we-are" className="mb-14 scroll-mt-24">
          <SectionNumber n={1} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Who We Are</h2>
          <p className="mb-4 text-white/70">
            FlockPilot is a multi-tenant farm management and ERP SaaS platform developed and operated by{" "}
            <strong className="text-white">Enro Agro Limited</strong>, a company registered under the laws of the
            Federal Republic of Nigeria (Corporate Affairs Commission). FlockPilot serves poultry farm operators,
            managers, supervisors, and related agribusiness personnel across Nigeria and Africa.
          </p>
          <div className="mb-4 rounded-xl border border-white/10 bg-white/[0.03] p-5">
            <h4 className="mb-2 text-sm font-bold text-brand-light">Data Controller</h4>
            <p className="text-sm text-white/70">
              Enro Agro Limited<br />
              2, Creek Road, Apapa, Lagos, Nigeria<br />
              Email: <strong className="text-white">hello@flockpilot.com</strong><br />
              Website: <strong className="text-white">flockpilot.com</strong>
            </p>
          </div>
          <p className="text-white/70">
            When we refer to <strong className="text-white">&quot;FlockPilot,&quot; &quot;we,&quot; &quot;us,&quot;</strong> or{" "}
            <strong className="text-white">&quot;our&quot;</strong> in this policy, we mean Enro Agro Limited acting as the
            operator of the FlockPilot platform. When we say <strong className="text-white">&quot;you&quot;</strong> or{" "}
            <strong className="text-white">&quot;your,&quot;</strong> we mean any individual accessing or using FlockPilot,
            including tenant administrators, farm managers, supervisors, operators, and any other authorized users.
          </p>
        </section>

        {/* S2 — Information We Collect */}
        <section id="information-we-collect" className="mb-14 scroll-mt-24">
          <SectionNumber n={2} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Information We Collect</h2>
          <p className="mb-4 text-white/70">We collect the following categories of information when you use FlockPilot:</p>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/10">
                  <th className="py-3 pr-4 text-left text-xs font-semibold uppercase tracking-wider text-brand-light">Category</th>
                  <th className="py-3 pr-4 text-left text-xs font-semibold uppercase tracking-wider text-brand-light">Examples</th>
                  <th className="py-3 text-left text-xs font-semibold uppercase tracking-wider text-brand-light">Source</th>
                </tr>
              </thead>
              <tbody>
                {dataCategories.map((row) => (
                  <tr key={row.category} className="border-b border-white/5">
                    <td className="py-3 pr-4 font-medium text-white">{row.category}</td>
                    <td className="py-3 pr-4 text-white/60">{row.examples}</td>
                    <td className="py-3 text-white/60">{row.source}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="mt-5 rounded-lg border-l-2 border-brand-light bg-brand-light/5 px-5 py-4 text-sm text-white/70">
            We do <strong className="text-white">not</strong> store raw payment card numbers or bank account credentials.
            Payment processing is handled by Paystack and is governed by their privacy policy.
          </div>
        </section>

        {/* S3 — How We Use Your Information */}
        <section id="how-we-use-your-information" className="mb-14 scroll-mt-24">
          <SectionNumber n={3} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">How We Use Your Information</h2>
          <p className="mb-4 text-white/70">We use the information we collect for the following purposes:</p>
          <ul className="mb-4 space-y-2 text-white/70">
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To create, manage, and maintain your FlockPilot account and tenant workspace</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To deliver core platform features including farm operations, finance/ERP, and HR management</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To auto-generate accounting journal entries from farm operational events</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To process payroll and HR-related workflows in compliance with Nigerian law (PAYE, Pension, VAT, WHT)</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To send transactional notifications via SMS and WhatsApp (powered by Termii)</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To monitor platform performance, detect errors, and improve reliability (via Sentry)</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To manage subscription billing, renewals, and payment lifecycle events</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To respond to support requests and communicate platform updates</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To enforce our Terms of Service and prevent fraud or abuse</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> To comply with applicable Nigerian law and regulatory obligations</li>
          </ul>
          <p className="text-white/70">
            We do <strong className="text-white">not</strong> sell your personal data. We do{" "}
            <strong className="text-white">not</strong> use your farm or financial data for advertising purposes. We do{" "}
            <strong className="text-white">not</strong> use automated decision-making that produces legal or similarly
            significant effects on you without human oversight.
          </p>
        </section>

        {/* S4 — Legal Basis for Processing */}
        <section id="legal-basis" className="mb-14 scroll-mt-24">
          <SectionNumber n={4} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Legal Basis for Processing</h2>
          <p className="mb-4 text-white/70">
            Our processing of personal data is grounded in the <strong className="text-white">Nigeria Data Protection Act 2023 (NDPA)</strong>{" "}
            and the <strong className="text-white">Nigeria Data Protection Regulation 2019 (NDPR)</strong>. The legal bases on which we rely include:
          </p>
          <ul className="space-y-2 text-white/70">
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Contract performance</strong> &mdash; processing necessary to deliver the FlockPilot service under our Terms of Service</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Legitimate interests</strong> &mdash; platform security, error monitoring, fraud prevention, and product improvement</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Legal obligation</strong> &mdash; compliance with Nigerian tax, labour, and financial regulations</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Consent</strong> &mdash; where we ask for and receive your explicit consent (e.g., marketing communications)</span></li>
          </ul>
        </section>

        {/* S5 — Data Sharing & Third Parties */}
        <section id="data-sharing" className="mb-14 scroll-mt-24">
          <SectionNumber n={5} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Data Sharing &amp; Third Parties</h2>
          <p className="mb-4 text-white/70">
            We only share your data with trusted third-party service providers who are necessary for us to operate
            FlockPilot. These parties are contractually bound to protect your data and may only use it for the
            specific purposes we authorize.
          </p>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/10">
                  <th className="py-3 pr-4 text-left text-xs font-semibold uppercase tracking-wider text-brand-light">Provider</th>
                  <th className="py-3 pr-4 text-left text-xs font-semibold uppercase tracking-wider text-brand-light">Purpose</th>
                  <th className="py-3 text-left text-xs font-semibold uppercase tracking-wider text-brand-light">Data Shared</th>
                </tr>
              </thead>
              <tbody>
                {thirdParties.map((row) => (
                  <tr key={row.provider} className="border-b border-white/5">
                    <td className="py-3 pr-4 font-medium text-white">{row.provider}</td>
                    <td className="py-3 pr-4 text-white/60">{row.purpose}</td>
                    <td className="py-3 text-white/60">{row.data}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-4 text-white/70">
            We may also disclose personal data if required to do so by law, court order, or a competent Nigerian
            regulatory authority, or to protect the rights, property, or safety of FlockPilot, our users, or the public.
          </p>
          <p className="mt-4 text-white/70">
            We will <strong className="text-white">never</strong> sell, rent, or trade your personal data to any third party for marketing purposes.
          </p>
        </section>

        {/* S6 — Data Retention */}
        <section id="data-retention" className="mb-14 scroll-mt-24">
          <SectionNumber n={6} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Data Retention</h2>
          <p className="mb-4 text-white/70">
            We retain your personal data for as long as your account is active or as needed to provide the FlockPilot
            service. Tenant data follows this lifecycle:
          </p>
          <ul className="mb-4 space-y-2 text-white/70">
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Active subscriptions:</strong> Data retained and fully accessible</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Cancelled subscriptions:</strong> Data retained in read-only mode for 30 days</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Expired subscriptions:</strong> Data retained for a further grace period before scheduled deletion</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Upon deletion request:</strong> Personal data purged within 30 days, except where retention is required by Nigerian law</span></li>
          </ul>
          <p className="text-white/70">
            Financial records (journal entries, payroll, invoices) may be retained for up to{" "}
            <strong className="text-white">7 years</strong> in accordance with Nigerian tax and accounting regulations,
            even after account closure.
          </p>
        </section>

        {/* S7 — Data Security */}
        <section id="data-security" className="mb-14 scroll-mt-24">
          <SectionNumber n={7} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Data Security</h2>
          <p className="mb-4 text-white/70">
            We implement technical and organizational measures to protect your personal data against unauthorized
            access, loss, alteration, or disclosure. These include:
          </p>
          <ul className="mb-4 space-y-2 text-white/70">
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> Encryption of data at rest and in transit (TLS/HTTPS)</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> Role-based access control (RBAC) with strict permission boundaries per user role</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> Multi-tenant data isolation &mdash; each farm organization&apos;s data is logically separated</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> Real-time error monitoring and anomaly detection via Sentry</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> Secure background job processing with Redis and BullMQ</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> Regular security reviews and dependency audits</li>
          </ul>
          <p className="text-white/70">
            While we take all reasonable precautions, no system is 100% secure. If you suspect a security breach
            affecting your account, please contact us immediately at{" "}
            <strong className="text-white">hello@flockpilot.com</strong>.
          </p>
        </section>

        {/* S8 — Your Rights */}
        <section id="your-rights" className="mb-14 scroll-mt-24">
          <SectionNumber n={8} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Your Rights</h2>
          <p className="mb-4 text-white/70">
            Under the Nigeria Data Protection Act 2023 and NDPR, you have the following rights regarding your personal data:
          </p>
          <ul className="mb-4 space-y-2 text-white/70">
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Right of Access:</strong> Request a copy of the personal data we hold about you</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Right to Rectification:</strong> Request correction of inaccurate or incomplete data</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Right to Erasure:</strong> Request deletion of your personal data (subject to legal retention obligations)</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Right to Restriction:</strong> Request that we limit how we process your data</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Right to Data Portability:</strong> Receive your data in a structured, machine-readable format</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Right to Object:</strong> Object to processing based on legitimate interests</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Right to Withdraw Consent:</strong> Withdraw consent at any time where processing is consent-based</span></li>
          </ul>
          <p className="text-white/70">
            To exercise any of these rights, contact us at <strong className="text-white">hello@flockpilot.com</strong>.
            We will respond within <strong className="text-white">30 days</strong>. If you are unsatisfied with our
            response, you may lodge a complaint with the{" "}
            <strong className="text-white">Nigeria Data Protection Commission (NDPC)</strong>.
          </p>
        </section>

        {/* S9 — Children's Privacy */}
        <section id="childrens-privacy" className="mb-14 scroll-mt-24">
          <SectionNumber n={9} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Children&apos;s Privacy</h2>
          <p className="mb-4 text-white/70">
            FlockPilot is a professional business management platform intended solely for use by adults in a commercial
            or agricultural business context. We do <strong className="text-white">not</strong> knowingly collect personal
            data from children under the age of 13.
          </p>
          <p className="text-white/70">
            If you believe that a child under 13 has provided us with personal information, please contact us at{" "}
            <strong className="text-white">hello@flockpilot.com</strong> and we will promptly delete that information.
          </p>
        </section>

        {/* S10 — Cookies & Tracking */}
        <section id="cookies" className="mb-14 scroll-mt-24">
          <SectionNumber n={10} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Cookies &amp; Tracking Technologies</h2>
          <p className="mb-4 text-white/70">
            The FlockPilot web platform may use cookies and similar technologies to maintain sessions, remember
            preferences, and analyze usage patterns. The FlockPilot mobile app uses local device storage (AsyncStorage)
            for offline functionality &mdash; this data remains on your device and is not shared with third parties.
          </p>
          <ul className="space-y-2 text-white/70">
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Essential cookies:</strong> Required for authentication and session management</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">Analytics:</strong> Anonymized usage data to improve platform performance</span></li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span><span><strong className="text-white">No advertising cookies:</strong> We do not use tracking pixels or ad networks</span></li>
          </ul>
        </section>

        {/* S11 — International Transfers */}
        <section id="international-transfers" className="mb-14 scroll-mt-24">
          <SectionNumber n={11} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">International Data Transfers</h2>
          <p className="text-white/70">
            FlockPilot is operated from Nigeria and primarily serves users within Nigeria and Africa. Some of our
            third-party service providers (such as Sentry) may process data in jurisdictions outside Nigeria. Where such
            transfers occur, we ensure appropriate safeguards are in place in accordance with NDPA requirements,
            including contractual protections with service providers.
          </p>
        </section>

        {/* S12 — Changes to This Policy */}
        <section id="changes" className="mb-14 scroll-mt-24">
          <SectionNumber n={12} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Changes to This Policy</h2>
          <p className="mb-4 text-white/70">
            We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal
            requirements, or for other operational reasons. When we make material changes, we will:
          </p>
          <ul className="mb-4 space-y-2 text-white/70">
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> Update the &quot;Last Updated&quot; date at the top of this page</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> Notify tenant administrators via email and/or in-app notification</li>
            <li className="flex gap-2"><span className="text-brand-light">&rarr;</span> Where required by law, seek your renewed consent</li>
          </ul>
          <p className="text-white/70">
            Your continued use of FlockPilot after any changes constitutes your acceptance of the updated Privacy Policy.
            We encourage you to review this page periodically.
          </p>
        </section>

        {/* S13 — Contact Us */}
        <section id="contact" className="mb-14 scroll-mt-24">
          <SectionNumber n={13} />
          <h2 className="mb-4 border-b border-white/10 pb-4 text-2xl font-bold">Contact Us</h2>
          <p className="mb-4 text-white/70">
            If you have any questions, concerns, or requests regarding this Privacy Policy or how we handle your
            personal data, please contact us through any of the following channels:
          </p>
          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
            <h4 className="mb-4 text-lg font-bold">FlockPilot Data Privacy</h4>
            <div className="divide-y divide-white/5 text-sm">
              <div className="flex gap-4 py-3">
                <span className="w-24 shrink-0 text-xs font-semibold uppercase tracking-wider text-white/40">Email</span>
                <a href="mailto:hello@flockpilot.com" className="text-brand-light hover:underline">hello@flockpilot.com</a>
              </div>
              <div className="flex gap-4 py-3">
                <span className="w-24 shrink-0 text-xs font-semibold uppercase tracking-wider text-white/40">Operator</span>
                <span className="text-white/70">Enro Agro Limited</span>
              </div>
              <div className="flex gap-4 py-3">
                <span className="w-24 shrink-0 text-xs font-semibold uppercase tracking-wider text-white/40">Address</span>
                <span className="text-white/70">2, Creek Road, Apapa, Lagos, Nigeria</span>
              </div>
              <div className="flex gap-4 py-3">
                <span className="w-24 shrink-0 text-xs font-semibold uppercase tracking-wider text-white/40">Website</span>
                <a href="https://flockpilot.com" className="text-brand-light hover:underline">flockpilot.com</a>
              </div>
              <div className="flex gap-4 py-3">
                <span className="w-24 shrink-0 text-xs font-semibold uppercase tracking-wider text-white/40">Regulator</span>
                <span className="text-white/70">
                  Nigeria Data Protection Commission (NDPC) &mdash;{" "}
                  <a href="https://ndpc.gov.ng" target="_blank" rel="noopener noreferrer" className="text-brand-light hover:underline">
                    ndpc.gov.ng
                  </a>
                </span>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* Footer */}
      <footer className="border-t border-white/10 px-6 py-8 text-center text-sm text-white/30">
        &copy; 2025 Enro Agro Limited. All rights reserved. &middot; FlockPilot is a product of Enro Agro Limited, registered in Nigeria.
      </footer>
    </main>
  );
}
